environment:
  build_version: 2.5.0

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(build_version)
  assembly_file_version: $(build_version)
  assembly_informational_version: $(build_version)
before_build:
- nuget restore src\stashbox.web.mvc.sln
- nuget update src\stashbox.web.mvc.sln -id Stashbox
build:
  project: src\stashbox.web.mvc.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
